### ISSUE TITLE
Module should not attempt to write to datastores if it is being used in a local place file

### ISSUE THREAD

**Issue by NobleDraconian** [boatbomber/SheetValues#4] opened 2021-04-23 23:32 UTC
Currently, as of bc9d427, the SheetValues module does not account for situations where it is being ran in a local place file. It attempts to write to datastores, and throws an error if it cannot write to them.

Instead, the module should completely ignore using datastores if it is in a local place file. This makes it easier to test systems that rely on this library without needing to manually publish.

**Comment by boatbomber** [comment] 2021-04-25 16:49
After some work, I realize that this issue is "unsolvable" in that the entire core of this module relies on DataStores, HttpService, and MessagingService- all three of which can only be used in a published place with permissions enabled.

This module simply *cannot* function in a vacuum.

**Comment by NobleDraconian** [comment] 2021-04-26 11:04
Why does it need datastores and MessagingService? From what I read, it seems like it uses them to cache data to prevent google's API from being spammed. Couldn't the module simply bypass that behavior & only use HttpService when in a local place file?

**Comment by boatbomber** [comment] 2021-04-26 16:10
I misunderstood your request, because this is actually a bug! It mishandles DataStore failure. Fixing now, thanks for noticing!

**Comment by boatbomber** [comment] 2021-04-26 16:14
Fixed in commit https://github.com/boatbomber/SheetValues/commit/bc0a5efa221fec66497413416a0fbb67388c793b. The problem was caused by a relic of the original prototype when it handled specific errors instead of generic.

**Closed as completed by boatbomber** 2021-04-26 16:14 UTC
Labels: bug
